# Generated by Django 6.0.4 on 2026-04-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("hire_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SchedulingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_consecutive_days", models.PositiveIntegerField(default=5)),
                ("mandatory_rest_days", models.PositiveIntegerField(default=1)),
                ("avoid_consecutive_nights", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#ffffff", max_length=7)),
                ("is_work_shift", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.employee",
                    ),
                ),
                (
                    "shift_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shifts.shifttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date")},
            },
        ),
    ]
